[appender.stdout]
kind = "console"

[appender.debug]
kind = "file"
path = "debug.log"

[root]
level = "warn"
#level = "debug"
appenders = ["stdout", "debug"]

[[logger]]
name = "archer"
level = "debug"
#level = "info"

[[logger]]
name = "archer::parser::css"
level = "trace"

[[logger]]
name = "html5ever"
level = "error"
